### ISSUE TITLE
Spell Template not appearing

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#104]
Is the spell template function supposed to be working yet?
I've ticked the Create a Template checkbox and set the size and type (e.g., for Igni - Size: "2" (m), Type: "Cone") but when casting from a character sheet nothing appears. Is there a step that I'm missing?

**Comment by AnthonyMonette** [comment]
I just tried it and it seems to work on my side. Are you sure that the spell in the character sheet has the create template box  checked?
If not you can contact me in discord so we can look at the problem together!

**Comment by Dillatr** [comment]
Yep, the box was ticked. I also made sure that the actor token is on the map and that a combat encounter is active in case those were required by chance. I also tried making new actors and spells post-update but that didn't produce any results either. The roll goes through and the spell details and roll appear in the chat, but nothing else happens apart from that. Also tested it using different spell types and template settings. I'm on the Foundry discord and happy to get in touch there. Dillatr#5050 (GMT+10)

![image](https://user-images.githubusercontent.com/91529833/135194472-2bcb2460-85f7-459b-af94-9b4fcfc70b5e.png)

**Comment by Dillatr** [comment]
After further testing, the spell template does work when the spell is cast from a monster sheet, but not from a character sheet for me.

**Comment by Dillatr** [comment]
I've been able to test out the bug with some of my players in case the feature was interacting weirdly with GM permissions. The spell template didn't generate for them when they cast a spell either despite the parameters for the spell template being set. It still only appears when the spell is cast from a monster actor sheet but not from a player actor sheet.

**Comment by AnthonyMonette** [comment]
I'll take a look today Hopefully i'll find something!

**Comment by AnthonyMonette** [comment]
Foundthe problem it will be solved in the next update :D
