### ISSUE TITLE
New Font...

### ISSUE THREAD

**Issue by mk1lolo** [AnthonyMonette/TheWitcherTRPG#112]
The new font is very large and all capitalized. It is difficult to read. And as the page in Spanish is larger, some skills do not fit in the line of text. Could the font be a little smaller or another typeface style?

**Comment by AnthonyMonette** [comment]
Yes I think it is causing more problem thant being immersive.  I'm considering removing it while searching for an other font style. well I won't remove it but in the system settings i'll put it to false by default.
