### ISSUE TITLE
Racial Bonus

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#125]
How nicely the armor is presented on sheets. Is it possible to present Racial Bonus (dwarven) as armor?

**Comment by AnthonyMonette** [comment]
What I did in my personal game is that I created a Natural armor item with a full cover and 2 SP everywhere

**Comment by Ulvtand** [comment]
mmm That was my first thought, Maybe in the headline (where it says SP) write "SP + BR" (Racial Bonus), as a reminder?

**Comment by AnthonyMonette** [comment]
Youy can now specify natural armor type in the armor item
