### ISSUE TITLE
Weight does not increase as quantity increases.

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#126]
Valuables.

**Comment by Ulvtand** [comment]
![image](https://user-images.githubusercontent.com/82996726/139696732-65a8f061-0a9f-4e01-96a1-a88eafc6234d.png)
quantity does not change, a "new" is added

**Comment by AnthonyMonette** [comment]
Well if the quantity is changed it will not change the weight since it is a single item weight.  The quantity * weight is calculated at the bottom of the inventory in the weight bar :)
