### ISSUE TITLE
Rolling silver damage & vulnerability when applying damage

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#136]
Would you be able to implement a way to be able to roll silver damage in addition to regular damage for weapons?
 Such as a checkbox into the weapon sheet for "Silvered" which creates a second text box for "Silver DMG". Since Silvered weapons only roll the extra damage against monsters vulnerable to silver, there's currently no way of rolling the needed damage for varying situations apart from manually rolling additional dice. This could be complemented with a "Apply Silver Damage" Check box when applying damage, similar to the Resistance checkboxes.

Also, it would be nice to have a checkbox to mark that the damage receiver is vulnerable to an attack and double the applied damage after SP calculation.

**Comment by AnthonyMonette** [comment]
GReat improvement,  I also added the oil damage! Thanks
