### ISSUE TITLE
connect coin with

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#139]
![image](https://user-images.githubusercontent.com/82996726/140932539-68785afb-2a3a-47d7-9bbd-b8f895b35b59.png)

**Comment by AnthonyMonette** [comment]
There is no need of an item it is now handle within the character sheet

**Comment by Ulvtand** [comment]
maybe, but for example loot with coin that is moved to PC sheet gives this result
