### ISSUE TITLE
On the Loot sheet, the qty is not increased

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#143]
![image](https://user-images.githubusercontent.com/82996726/140969827-fc3fd36e-ac73-4f59-97aa-a188d2bcaea3.png)

**Comment by AnthonyMonette** [comment]
I'll need more clarrificationa bout this. What was the specific action here? 
Did you drag the item from one sheet to another? What was the initial qty in each sheet?

**Comment by Ulvtand** [comment]
Most items do not increase in quantity when the next one is moved there

**Comment by AnthonyMonette** [comment]
I just tried it and it seems to work.
![screen1](https://user-images.githubusercontent.com/12412198/141333535-47bcc489-e4b4-4cc7-a831-9d8df1e9b6b8.JPG)
![screen2](https://user-images.githubusercontent.com/12412198/141333549-b645db7b-64f6-4808-a565-733dc0ead392.JPG)
![screen3](https://user-images.githubusercontent.com/12412198/141333561-1daabe6f-f178-4c2f-b30f-6da833c98815.JPG)

**Comment by Ulvtand** [comment]
I just did a new test.
Works: moving between sheets
Does not work: from Items or Compendium

**Comment by Ulvtand** [comment]
Same thing for PC sheets AND after adding 50 Byzantines, the sheet counts as if it were 100 pcs. When I then add 50 more, there will be no change in weight.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/82996726/144995848-a21757c3-6eb2-4f4f-8a1b-e3767a00393d.png">
<img width="604" alt="image" src="https://user-images.githubusercontent.com/82996726/144995893-d5b6ac25-fa9c-4429-8000-405b493e70bd.png">
<img width="605" alt="image" src="https://user-images.githubusercontent.com/82996726/144995949-d9b7ef37-9fd4-4966-8e91-1ed337729c3b.png">

**Comment by Batziy** [comment]
With this setup. If I move the Noon Wraith Mutagen from 123 to 321 I get a null value for qty and the sheet is rendered useless (locks up). Has to go into the code to change the qty to 1.

https://gyazo.com/7685d32e1ef89665a50715688051ba1d
