### ISSUE TITLE
Question about translation

### ISSUE THREAD

**Issue by DarkLeopard** [AnthonyMonette/TheWitcherTRPG#145]
Hi. I'm new to the topic. I want to add translations for things, monsters, etc. How to do it?
The variables are missing in the general translation file ("lang/*.json"). As I understand it, what I need is stored in a folder "packs" in the form of a database, but I do not understand if there is a translation mechanism.

**Comment by AnthonyMonette** [comment]
The translation mechanism is automatic.  You only need to do a *.json file with the language code of the translation and in the systme.json Add an item int the languages attribute:
```
"languages": [
      {
        "lang": "en",
        "name": "English",
        "path": "lang/en.json"
      },
      {
        "lang": "es",
        "name": "Español",
        "path": "lang/es.json"
      }], 
```

**Comment by DarkLeopard** [comment]
Thanks for the quick response! I have added translations to all of the available keys.
https://github.com/AnthonyMonette/TheWitcherTRPG/pull/144

My original question has to do with missing translations in the folder (lang/*.json). For example:
* file "packs/witcher-character-generator.db"
* transtalion for "name": "Family and Parents: Northern"

**Comment by AnthonyMonette** [comment]
Oh for the tables ands evrything, hmmm I've never really done it.  Let me check it out, but you could probably duplicate them an translate them in a new local compendium

**Comment by DarkLeopard** [comment]
OK, thanks.

I'm not familiar with the functionality, I'm doing the translation for our DM. Does the program have functionality for selecting a specific compendium?

If I make a new local compendium in a new language, will I add it to the repository? I think there will be people who want to use it.
