### ISSUE TITLE
Create loot from monster cheet.

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#146]
Add a button on the Loot tab on monster that generate a loot item with all the loot the monster have. Also rolls the dice for loot that have 1d6 for example.

**Comment by AnthonyMonette** [comment]
You can curently Drag and Drop an item that has *d* in Qty and it will roll the value. 
I'm not really sure qhat do you mean by generating a loot item with all the loot. What the purpsose?

**Comment by Ulvtand** [comment]
maybe "1d6 mundana items" thinks that FVTT also rolls on the table for "mundana items"?

**Comment by Batziy** [comment]
A loot sheet is what I mean. I like to create one when all the enemies are dead for my player to rummage through. Just a little shortcut. Instead of dragging every item 6 times and can just press a button and specify that I want all the loot times 6 for example.

**Comment by Ulvtand** [comment]
Variant of #146

![image](https://user-images.githubusercontent.com/82996726/141440232-bc61aa66-6d54-4d09-bb29-6d15a88a5988.png)
A button, see above where, that copies the loot below to an existing loot sheet.

I have made a loot sheet called "common resources" to which all PCs have full rights
