### ISSUE TITLE
Loot & shop

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#151]
* drag & drop does not work, nothing happens
* When trying to shop, see picture 1. Items come to inventory but can not be deleted, see picture 2
1) ![image](https://user-images.githubusercontent.com/82996726/142038138-1943765a-cd8d-497f-b549-3f0487b8b04a.png)
2) ![image](https://user-images.githubusercontent.com/82996726/142038502-639fed6a-3ca5-4238-8510-5b08fbc669cc.png)

PC has the right "owner" on both loot and character sheets and has the token on scene

**Comment by AnthonyMonette** [comment]
Hmmm, this is a tricky problem, could you make sure that the PC has ownership on the token Also ?

**Comment by AnthonyMonette** [comment]
and could you tell me if the token are link to the orignial actor

**Comment by Ulvtand** [comment]
what I remember so, yes. I'm going to double check when I'm home again. in about 12 hours.

**Comment by Ulvtand** [comment]
Yes and yes

Then I discovered that loot sheet does not update Qty, from PC to Loot
