### ISSUE TITLE
Character Sheet not saving data

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#153]
The text fields in the Profession & Race tab above the coloured squares do not retain data after closing and re-opening a character sheet.

**Comment by AnthonyMonette** [comment]
Hello ! I just tried it and it seems to work could you sent me a screenshot with the specific location that isn't saved?

**Comment by Dillatr** [comment]
These empty text fields, which I presume is for the name of the skill tree branch, keep clearing themselves when I try to fill them in.

![image](https://user-images.githubusercontent.com/91529833/143202250-61a7a0e2-3519-4267-8f1a-b50711bd373a.png)
