### ISSUE TITLE
target

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#157]
When you have a target and roll for weapons, it automatically retrieves defensive value and presents the result.

And applies the damage

**Comment by Dillatr** [comment]
I'm a bit confused about how this automation will streamline things? You would still need to select what type of defensive action the target is taking as well as any modifiers to their defence roll such as Ganging Up. At that point there is already the option to right-click the attack roll to initiate a defence action, and right-clicking damage to apply damage (which also needs certain elements to be specified to apply the damage correctly).

I don't intend to come off as harsh if it does but I'm struggling to picture how the automation would work in practice. Would you be able to clarify by what you mean?

**Comment by Ulvtand** [comment]
> I don't intend to come off as harsh if it does but I'm struggling to picture how the automation would work in practice. Would you be able to clarify by what you mean?

No danger, I want some features that may already exist. I will test what you say and reformulate me so that we hopefully sweeten the product

**Comment by Ulvtand** [comment]
As I said, I wanted features that already exist.

But which I did not know about. Maybe time to write some wiki?
