### ISSUE TITLE
Add Support for Chat Portrait

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#158]
https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait

**Comment by AnthonyMonette** [comment]
This one is already working. I use it in my game and it seemed to work fine? have you encountered any problem?

**Comment by Ulvtand** [comment]
not all parts work, it's late here so you'll get an answer tomorrow

**Comment by Ulvtand** [comment]
It works well now, but not when I wrote issues. 😄
