### ISSUE TITLE
Damage to armor and weapons

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#176]
Is it possible on a monster sheet to keep track of the damage that, for example, Nilfgaard's soldiers' equipment receives. If it is a long battle with many small injuries, the armor can look like a sieve

**Comment by Dillatr** [comment]
On the monster sheet, there's a section for armour SP that will automatically be reduced when ablated via the Apply Damage function
![image](https://user-images.githubusercontent.com/91529833/145526447-9006fbf8-ac04-4e52-975b-2ee59c4689f6.png)

When creating a weapon for monsters, there is also the REL field
![image](https://user-images.githubusercontent.com/91529833/145526537-1614016e-4dc8-4651-bf9a-6511bf39bb4b.png)

Hope that answers your question.

**Comment by Ulvtand** [comment]
nop

**Comment by Dillatr** [comment]
could you clarify what you mean by tracking damage to equipment?

**Comment by Ulvtand** [comment]
To reduce all misunderstandings, we will open a discussion in discord and with a split screen?
