### ISSUE TITLE
fumble and crit

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#177]
<img width="153" alt="image" src="https://user-images.githubusercontent.com/82996726/145525802-b0a1a3f6-5129-45f9-98fb-5578eb7d66f1.png">
the buttons in the chat have stopped working

**Comment by Dillatr** [comment]
![image](https://user-images.githubusercontent.com/91529833/145526648-2eee58b2-6973-4a0c-9206-587aab042bfa.png)

I just gave it a test and it seemed to work for me. Have you made sure that everything is up-to-date? If so, there may be a module which is causing issues since the chat message appears to be broken in your image.

**Comment by Ulvtand** [comment]
Everything has been updated since some min. It usually works. I was more aware of it from the PC side today and then it does not work the times I tested

**Comment by Ulvtand** [comment]
I have all systems and modules as updated as I can, I check every day that I use Foundry

**Comment by Dillatr** [comment]
Is there a module you are using to give the chat timestamp? Just a random guess but that seems to be interacting with the chat message generation and could be causing interference? If it is a module, could you try disabling it and testing it again?

**Comment by Ulvtand** [comment]
To reduce all misunderstandings, we will open a discussion in discord and with a split screen?

**Comment by Dillatr** [comment]
Sure, DM or is there a server?

**Comment by Ulvtand** [comment]
server, what's your name on discord?

**Comment by Dillatr** [comment]
I'll be in the Foundry server FVTT-voice-discussion voice chat

**Comment by Dillatr** [comment]
![image](https://user-images.githubusercontent.com/91529833/145528681-33d7bbec-ed48-4400-9a0b-1b634bc66518.png)
