### ISSUE TITLE
Block defence automatically reduces Rel. even if defence failed

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#179]
I've noticed that using the block defence action automatically reduced weapon/shield Rel. regardless if the defence was successful or not when it should only be reduced after a successful block.

I'm not sure the difficulty of writing code to get the defence roll to compare itself against the attack roll which prompted the defence.
image

An alternative could be to have an option to right-click the block defence chat message to reduce the Rel. rather than needing to revert the Rel. reduction manually each time a block failed.

**Comment by AnthonyMonette** [comment]
In the book it says "Roll your weapon skilll to negate an attack with your weapon. Roll Melee to negate an attack with a shield .  Whichever you parry  with takes 1 point of damage"  It doesn't precise that it must be successfull to remove the reliability.  But i'll ask in the R tsalorian discord just to make sure ! Good question here !

**Comment by Ulvtand** [comment]
If you fail completely, that is, do not succeed in getting something between the weapon and yourself, then the object should not be reduced in Rel.
