### ISSUE TITLE
Add Description to Fomulaes and Diagrams

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#180]
Add description so you know the the crafted item does so you don't have to go look for it. Also maybe change the component list of Diagrams to be more like the effects table for weapons. A list in a text box is a bit jarring.

**Comment by AnthonyMonette** [comment]
I added the description in the diagram. Se when you are editing it, you can drag and drop the specific item in this field to link the item to the diagram!
