### ISSUE TITLE
Normal/Silver damage

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#184]
The witcher silver sword has 1d6+2 normal damage and 3d6 silver damage. But when applying damage and you use the "resistance to non silver damage" option all damage is calculated as silver damage. Also I might be wrong but shouldn't damage be rounded down. Looks like it's always rounded up.

**Comment by AnthonyMonette** [comment]
It doens't precise if it's rounded up or down,  so I'll let it as it is now.  For the silver damage it depends on how you setup rour weapon normally for silver weapon in the damage i'll put 1d6+2 and add the silver(3d6) in effects.  When applying damage you can select the number of silver damage, applied or roll it separately. I'm pretty sure there was somewhere saying that if there is silver dmg all the dmg is considered silver, I'll  to check it

**Comment by Batziy** [comment]
Yeah you might be right about the silver damage. Sound weird halving first den having full damage.

**Comment by Dillatr** [comment]
In the errata, they mention that resistance (e.g., bleeding resistance) halves the damage, rounded down. I assume this would apply to other instances when halving. From what I remember, almost all instances mentioning rounding say to round down as this is the common practice for the Interlock system that Witcher is built upon.

**Comment by Batziy** [comment]
> In the errata, they mention that resistance (e.g., bleeding resistance) halves the damage, rounded down. I assume this would apply to other instances when halving. From what I remember, almost all instances mentioning rounding say to round down as this is the common practice for the Interlock system that Witcher is built upon.

Yeah that was my assumption too. The only thing not rounded down is movement in squares.
