### ISSUE TITLE
Separate Range and Mele Weapons

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#19]
Separate Range and Mele Weapons and make range weapons to be able to equip different ammo that change the type and effect of the attack.

**Comment by AnthonyMonette** [comment]
How would you separate Range and Melee Weapons? There is already a Melee Bonus checkbox in the weapons.  
And yess change the ammo is a good idea!

**Comment by Batziy** [comment]
Was thinking you could remove for example weapon range from normal weapons but I see now that some polearms have range so would be kinda redundant.

**Comment by AnthonyMonette** [comment]
and you also have thrown weapons that are melee and have range also.

**Comment by AnthonyMonette** [comment]
I think on this disscusion I will close this issue and create a new one for the ammunition!

**Comment by Batziy** [comment]
Exactly :) do it ^^
