### ISSUE TITLE
Error apply dmg

### ISSUE THREAD

**Issue by mk1lolo** [AnthonyMonette/TheWitcherTRPG#193]
Hello. I get this error when trying to apply the damage. What can this error be due to?
![image](https://user-images.githubusercontent.com/44495368/147230323-782feecc-a173-4d4a-8a14-e22db59efb3c.png)

**Comment by mk1lolo** [comment]
the damage does not apply it and that message comes out

**Comment by mk1lolo** [comment]
![image](https://user-images.githubusercontent.com/44495368/147244011-5899e3de-c82a-4118-8115-0246e45e0c96.png)

**Comment by Batziy** [comment]
Had the same problem. Prior to 0.9 update though. Have not tested after

**Comment by mk1lolo** [comment]
True I am in the 8 still. Tomorrow I update at 9 and test

**Comment by soltysek** [comment]
9 does not work right now, my PR fixes some things but not all..
I'll try to look at this and fix in my PR when I have some time during christmas. Unless @AnthonyMonette does this quicker ;)

**Comment by soltysek** [comment]
This should be fixed now after merging my v9 support PR.
