### ISSUE TITLE
Hidden monsters not showing up on Combat Tracker

### ISSUE THREAD

**Issue by yemyatko** [AnthonyMonette/TheWitcherTRPG#194]
I noticed that hidden tokens (characters) added to combat tracker does not appear on it.  They are still on combat tracker (I just learnt that by using turn marker) but they don't show up on the tracker list.

**Comment by etfortin** [comment]
I also have the issue and tried to understand why
After comenting the block:
.hidden { 
  display: none; 
} 
in system-styles.css the problem disapear.
Not sure why this css is used so I just patch it locally but the solution may help the dev

**Comment by AnthonyMonette** [comment]
Thanks for the info I changed it to invisble instead!
