### ISSUE TITLE
Unable to roll from character/monster sheet

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#196]
Unable to roll, gets stuck at the modifier box and returns error message as shown below. All modules are disabled and both Foundry and Witcher system are up-to-date. Also occurs when modifier value is set to another value or empty.

![Screenshot 2021-12-28 235213](https://user-images.githubusercontent.com/91529833/147568144-dcd7756b-0b04-4998-b555-67579ee8ab59.jpg)

![image](https://user-images.githubusercontent.com/91529833/147568281-08e7b6b6-4213-4d23-ac77-2feda51a2c6a.png)

**Comment by AnthonyMonette** [comment]
a new version has been released for foundry v9, let me know if the issue is still there
