### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Maxidag** [AnthonyMonette/TheWitcherTRPG#198]
Hi I have problem with installation witcher to my foundry i have foundry version 0.8.9.

when I click to instalation , installation start and on the end apeare message: Installation failed: Cannot set property "instaled" of null.

Can you help me?

BR Jarosalv

**Comment by AnthonyMonette** [comment]
upgrade your foundry with the stable V.9 it should install properly after

**Comment by AnthonyMonette** [comment]
let me know if you still have the issue after.
