### ISSUE TITLE
Applying damage to left leg does not reduce Armor

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#201]
As the title says. The issue is only present when applying damage to the L .Leg - damage is applied but armour remains the same. This happens for both Character and Monster actor sheets. I've tested the other damage locations and they work fine.

**Comment by AnthonyMonette** [comment]
Strange I just tried it and it seems to work. Could you send me a little bit more details like : what was the amount of damage originaly, what is the SP to the Left leg precisely, what damage type, what armor type, what was the damage type and when you apply damage there should be a chat message could you send me a screenshot of this one ?

**Comment by Dillatr** [comment]
Below is are the damage rolls and current monster HP and amour.
![image](https://user-images.githubusercontent.com/91529833/148766000-d2ef0c86-45ce-4249-9a51-4fc6447f6a4f.png)

Damage instances applied to Torso (first damage), L. Leg (second damage with missing SP Value) and R. Leg (third damage)
![image](https://user-images.githubusercontent.com/91529833/148766356-a05f0caf-9b57-414e-9adb-b5b59eff89d4.png)

Same as above but with a player character sheet
![image](https://user-images.githubusercontent.com/91529833/148766773-14fe1a96-c329-4336-954d-33f0fc29b706.png)

Damage instances applied to Torso (first damage), L. Leg (second damage with missing SP Value) and R. Leg (third damage)
![image](https://user-images.githubusercontent.com/91529833/148766865-235b1e1c-ecc0-4907-a41d-35f79fee3ef6.png)

**Comment by Dillatr** [comment]
Also tested using other damage types, issue still occurs regardless of damage type (S/P/B/E).

Slashing: Images from previous comment

Piercing:
![image](https://user-images.githubusercontent.com/91529833/148767160-e4a9bf7f-e135-40d1-8ebe-e1ebda4ace82.png)

Bludgeoning:
![image](https://user-images.githubusercontent.com/91529833/148767273-6a36b95e-9315-42e5-ac8b-3a8e24931dc0.png)

Elemental:
![image](https://user-images.githubusercontent.com/91529833/148767463-26dd0235-1f4d-4e7a-abb8-12bffa11fec8.png)


Also to note, no errors appear to be present in the Console
![image](https://user-images.githubusercontent.com/91529833/148767543-babc4378-7429-48f9-bb9d-21c9ff98d9a8.png)

**Comment by AnthonyMonette** [comment]
Found it! it was specificly when you change the body location in the apply Damage Thanks for your help !:D
