### ISSUE TITLE
Make it possible to drag and drop components

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#203]
Because the drag and drop function is in Foundry
<img width="385" alt="image" src="https://user-images.githubusercontent.com/82996726/148509797-a9e7f749-7161-45af-b595-8e7d10b3b1f2.png">

**Comment by AnthonyMonette** [comment]
You can do it in the Description directly

**Comment by Ulvtand** [comment]
What I was thinking of is #141  and it does not work if the ingredients are to be in "text form"
