### ISSUE TITLE
Fumble does not count correctly

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#208]
R. Talsorian Games video about Witcher, https://youtu.be/_H09AtOZweg?t=352. There they record fumble from 5:52 and at 6:12 **the speaker says that the original "1" should be counted.**

In the first box it is correct but the sum in the second box is wrong.

![image](https://user-images.githubusercontent.com/82996726/149127189-77b75e4b-2b77-4122-b02b-0d9247bf77f3.png)

**Comment by AnthonyMonette** [comment]
This was already answered.  In the book Page 156 in Criticals and Fumbles. It clearly says you substract your fumble to your base. With the same example from the book:
 if you roll 1 on a swordmanship check And you have 7 in Ref +6 in swordmanship.  You must roll your fumble value and let's say it's 7. your roll would bring you to a total of 6  (This does not includes your initial 1)
