### ISSUE TITLE
Add armor slots and separete sheet from Shields

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#21]
Add Head, Torso and Legs dropdown for armor and an equip button so you can easily see witch item is equipped and what stats you have on part.

**Comment by AnthonyMonette** [comment]
The drop down has been added in addition of the resistances,  but not the equipped  attribute

**Comment by Batziy** [comment]
We should also add a current SP of total SP on item for easy access, So players can change it on the fly

**Comment by AnthonyMonette** [comment]
This has been completed
