### ISSUE TITLE
Problem with the Reputation

### ISSUE THREAD

**Issue by JhaelenTerear** [AnthonyMonette/TheWitcherTRPG#210]
Hello,

When I try to make a Reputation Save or Face-Down, no roll is accomplished and I have an error in the console.

![image](https://user-images.githubusercontent.com/58259514/149168104-ca0ce9be-6e94-46ee-99f8-b1a6ed4bdd1b.png)

**Comment by AnthonyMonette** [comment]
Could you screen shot and send here your reputation's modifiers. Thanks!

**Comment by JhaelenTerear** [comment]
Sure : 
![image](https://user-images.githubusercontent.com/58259514/149231989-ef079dbf-3da1-4b58-9681-20b1e7a7bb90.png)
But it occures even if there is no modifiers.

**Comment by AnthonyMonette** [comment]
If you create a completly new character and roll directly the face down does it do the same thing ?

**Comment by JhaelenTerear** [comment]
With a brand new char, it worked perfectly. Weird.

**Comment by JhaelenTerear** [comment]
I made some more test for this : I'm thinking the issue is linked to the fact that is a space in labels.

This one is NOT OK
![image](https://user-images.githubusercontent.com/58259514/149653523-b72bc4cc-0a54-4d4b-8a1f-960e18493e34.png)

This one is OK
![image](https://user-images.githubusercontent.com/58259514/149653544-7f5af77c-7ad7-4a37-9c46-69c80acf3257.png)

Same char, differents labels.
