### ISSUE TITLE
What is the purpose of the button Crit/Fumble on the character sheet ?

### ISSUE THREAD

**Issue by JhaelenTerear** [AnthonyMonette/TheWitcherTRPG#212]
Hello,

I read all the release notes that you published, and I can't figure the purpose of the button Crit/Fumble.

![image](https://user-images.githubusercontent.com/58259514/149171626-21daef06-844d-4c3f-b98d-db513c22e72b.png)

**Comment by AnthonyMonette** [comment]
It's only to roll 1d10 that will explode on 10.  So if you Roll let's say an awareness yo got a 1.  You can click on this  Crit/Fumble to roll 1d10 that explodes on 10 and add it to your roll. Or if it's a fumble you subtract it to your base.

**Comment by JhaelenTerear** [comment]
Okay, I thought this mecanic was already added on regular rolls. When you roll a 1 or a 10 on a roll, there is a button that allows the reroll.

**Comment by AnthonyMonette** [comment]
yeah It is exacly the same thing :)
