### ISSUE TITLE
Create a dropdown for Social Standing

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#218]
Add a dropdown on you character sheet to change you social standing. So you can easily change from Equal to Hated if you are a Human when entering Dol Blathanna to get the -2 to Seduction, Persuasion and Leadership. Also maybe add when you roll one of these skills to ignore social standing. If for example you interact with a human.

**Comment by JhaelenTerear** [comment]
Great idea !
