### ISSUE TITLE
Export to loot

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#220]
Add option to "Export to Loot" do specify how many times the loot should be rolled. For example if my grupe kills 10 wraiths it's kind of annoying to export the loot 10 times to 10 individual toot items, then I need to change permission on all of them so they can take what they want. Instead make an option so I can just roll the loot 10 times in the same loot item and put it out so player can rummage around in one loot sheet.

**Comment by Ulvtand** [comment]
Alternatively, perhaps to a default loot sheet? I myself have made a loot sheet that all players "own" this makes it easier for me to hand out "items"

**Comment by Batziy** [comment]
Yeah I kinda do the same. Put all loot in a chest and plonk it down in the middle of the map for my players to rummage through :P

**Comment by amanwing** [comment]
It would be great if it would ask for a multiplier if you click on the create loot button on the monster sheet.
