### ISSUE TITLE
Drag and drop classes problems

### ISSUE THREAD

**Issue by amanwing** [AnthonyMonette/TheWitcherTRPG#221]
![grafik](https://user-images.githubusercontent.com/66251265/150805187-bf472797-24e1-4395-9e09-dfc05ddff280.png)
It seems that the character sheet has some problems with drag and drop classes. If you drag and drop a class on the sheet it shows html (at least I think it does). Please see picture

**Comment by soltysek** [comment]
duplicate of https://github.com/AnthonyMonette/TheWitcherTRPG/issues/211
