### ISSUE TITLE
Monster Sheet Derived Values Not Correctly Calculated.

### ISSUE THREAD

**Issue by RedneckRPGer** [AnthonyMonette/TheWitcherTRPG#223]
The derived values:
HP (Base *5), Stamina (Base *5), Encumbrance (Body *10), Run (Speed *3), Leap (Run/5) are not calculating properly

On the Bandit (Image attached) they should be HP: 20, Stamina 20, Encumbrance 40, Run 9, Leap 1.

![Witcher-Calc_Error](https://user-images.githubusercontent.com/68085825/151373186-7a72ea00-177a-4c23-b6e9-db72982e51db.png)

Leap is only correct because it has a floor of 1.

Have not tested if same errors are present on Actor Sheet.

**Comment by Ulvtand** [comment]
if you adjust HP from 0 to 5 or 20, the other values will be adjusted correctly

the sheet adjusts according to how much damage you have

**Comment by RedneckRPGer** [comment]
But the HP is the derived value?

Moreover, that doesn't account for the Encumbrance or Run values not being correct.

**Comment by Ulvtand** [comment]
The first number is the current HP and the latter is the maximum. According to the image you sent, the current HP is "0" and will receive modifications to STATs accordingly.

Try changing from 0 to, for example, 10 to see if there will be any change

**Comment by Ulvtand** [comment]
This is what it looks like to me

![image](https://user-images.githubusercontent.com/82996726/151627521-9a5bae49-d003-4b0a-bfa9-9f6350ce09e2.png)

**Comment by RedneckRPGer** [comment]
Thanks for getting back to me.

Ah, I think I see what you mean. The derived value doesn't change until some form a "user input" has happened, be that entering "current HP" or "tabbing" through the field.  It then updates - is that correct?

**Comment by Ulvtand** [comment]
Yes

**Comment by RedneckRPGer** [comment]
Many Thanks

**Comment by Dillatr** [comment]
@RedneckRPGer I recommend closing the issue thread if resolved so Anthony knows it's not something to investigate
