### ISSUE TITLE
Deadly wounds are healing

### ISSUE THREAD

**Issue by DKtric3L** [AnthonyMonette/TheWitcherTRPG#240]
Deadly wounds should not heal, but they heal after the time expires in the character's profile when pressing "Heal". Crutch - I write a large numerical value in the day counter to avoid this. 
Also it'll be nice if wounds changing char stats automatically, cuz for now i have to create wounds buffs.

**Comment by AnthonyMonette** [comment]
If you set the healing time to 0 it will never heals now
