### ISSUE TITLE
Can't expand any items in actor sheet as GM

### ISSUE THREAD

**Issue by Xywenx** [AnthonyMonette/TheWitcherTRPG#244]
When I try to epxand any items by pressing the "i" next to them nothing happens. My players seem to be able to do it just fine, but as GM I can't. I have no modules activated. And latest version. Tried to shut down world and start again, didn't help. No error in console.

![grafik](https://user-images.githubusercontent.com/85259241/187260097-0623d47d-4502-4d99-8594-9dbcd2bcbdd7.png)

**Comment by AnthonyMonette** [comment]
Hi, there was an issue with the version 0.81 can you confirm that your are on the latest 0.83?

**Comment by Xywenx** [comment]
Yup, I'm on 0.83

![grafik](https://user-images.githubusercontent.com/85259241/187299949-e9b78c9f-b7e1-4dd8-a35f-ceefc3f3ce5a.png)

**Comment by AnthonyMonette** [comment]
okay, It seems I cannot replicate the problem, which version of foundryvtt ar eyou using ?

**Comment by Xywenx** [comment]
Version 9.238

**Comment by AnthonyMonette** [comment]
Hmm I just tested on this version and seems to be fine . When you have some time could you try and log in as one of your player and see if you can open it?

**Comment by Xywenx** [comment]
Just tried it out. Logged in as a player who could use the button earlier and it didn't work for me. Could it be something on my side then?

**Comment by Xywenx** [comment]
Okay, I've found a solution. I tried a different browser, Edge this time and it worked. For some reason there's issues with Firefox.
