### ISSUE TITLE
Issue dragging and dropping items from the inventory v0.85

### ISSUE THREAD

**Issue by MemoriasdeunDragon** [AnthonyMonette/TheWitcherTRPG#250]
Hello, having updated to v 0.85, now, in my current game is not possible to drag and drop items from the items section to the characters. 
FoundryVTT version 10 build 284.
Has anyone more experimented this issue?

Thank you

**Comment by TheMOELANDER** [comment]
Same trouble here.

**Comment by Tvejzer** [comment]
Yep, same issue, same version, same build

**Comment by MemoriasdeunDragon** [comment]
I have been trying some things today and v0.83 works Vito foundryvtt v10.284, just some problems with tables when rolling from a macro using advances macros module.
Regards

**Comment by Tvejzer** [comment]
> I have been trying some things today and v0.83 works with foundryvtt v10.284, just some problems with tables when rolling from a macro using advances macros module. Regards

How do you downgrade though?

**Comment by MemoriasdeunDragon** [comment]
A friend, sent me a security copy of v0.83, I uninstalled the 0.85 and copy in the data/ system folder the 0.83 version

**Comment by AnthonyMonette** [comment]
I'm currently working for V10 migration. it should be available in a couple days ! Sorry for the problem that it is causing!

**Comment by Tvejzer** [comment]
> I'm currently working for V10 migration. it should be available in a couple days ! Sorry for the problem that it is causing!

Thank you for developing the module!

**Comment by MemoriasdeunDragon** [comment]
Please do not apologise, thank you very much for the really good job you are doing.

**Comment by TheMOELANDER** [comment]
Yes, please do not apologize. We only want to help you, so you know it's a widespread issue. You're doing amazing work!

**Comment by AnthonyMonette** [comment]
Thanks for the good words! :D  Actually the V10 migration is going pretty good right now and probably will be available today.  Everything has been changed, I'm testing everything for sanity check and will deploy the new version soon enough :)
