### ISSUE TITLE
v10 compatibility fields are not in the new manifest style

### ISSUE THREAD

**Issue by rikmarais** [AnthonyMonette/TheWitcherTRPG#265]
Hi there 👋 
Nothing major here but we noticed that the `manifest.json` has compatibility fields in the v9 style rather than the new v10 style. This can cause compatibility issues with certain systems that rely on the new flags for v10 manifests, and should probably be updated.

![image](https://user-images.githubusercontent.com/34374883/193912077-daabddc0-bdaa-4ec7-a7f4-6ed0b001c965.png)
![image](https://user-images.githubusercontent.com/34374883/193912084-9d76a813-3da0-48a1-aed7-44a64a2234cc.png)
https://foundryvtt.com/article/migration/

**Comment by Batziy** [comment]
This is fixed in the Dev branch. Just have to merge it to the main :)
