### ISSUE TITLE
Swordsmanship label bug

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#272]
Swordsmanship button not displaying correctly in character sheet and monster sheet.

![image](https://user-images.githubusercontent.com/91529833/196409772-f93076c6-202c-4c7d-b9cb-f76067f9549e.png)

**Comment by TheMOELANDER** [comment]
Ah! So it's not just the german stranslation that has this bug!

**Comment by Dillatr** [comment]
Found that this only applies to existing character sheets, must have been during an update. Newly created character sheets are labelled correctly.
