### ISSUE TITLE
Unable to edit Race & Profession

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#276]
In the Race & Profession tab for the character sheets, you can edit the titles of the skill trees and racial perks. But the actual text fields under them do not save any changes made. Text from previous versions is retained but new changes are not saved.

**Comment by AnthonyMonette** [comment]
This seems to be a limitation when editing items in character sheet whit the new edit box. 
I`ll remove the edit button from this screen but there is still an edit button beside the delete one that still work
