### ISSUE TITLE
Fumble calculation issue

### ISSUE THREAD

**Issue by DKtric3L** [AnthonyMonette/TheWitcherTRPG#277]
![изображение](https://user-images.githubusercontent.com/105752167/204092252-cdfe9b4e-0afd-48d8-8b7b-c359f1717e52.png)
The final value should be 18, but for some reason it always gives out one more. Why?
Or does it take into account the unit from the first check?

**Comment by AnthonyMonette** [comment]
Yep, in witcher TRPG the crit fumble doesn`t take in account the first "1" rolled.
