### ISSUE TITLE
Alchemy and Craft itens

### ISSUE THREAD

**Issue by pedroaugustobt** [AnthonyMonette/TheWitcherTRPG#290]
Alchemy and Creation already working? Or is the code still being built?

I'm testing it inside Foundry and it hasn't worked...

**Comment by LinkDragmire** [comment]
what exactly did you test? Creating an item in a players inverntory from a diagram is working, as long as all materials are in the inventory

**Comment by pedroaugustobt** [comment]
> 

the name of the diagram has to be the same as the item in the compendium

**Comment by AnthonyMonette** [comment]
@pedroaugustobt could you confirm if this is still an issue, Thanks!

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt could you confirm if this is still an issue, Thanks!

Currently working :)
