### ISSUE TITLE
Full stop ability does not work

### ISSUE THREAD

**Issue by mk1lolo** [AnthonyMonette/TheWitcherTRPG#292]
Armor stop does not work on characters.
D.E: the system is abandoned?
![image](https://user-images.githubusercontent.com/44495368/228374798-a5223872-c7f6-40af-b676-187449b11892.png)

**Comment by Melkkart** [comment]
I hope not, the armor problem is solved, visit 
https://github.com/AnthonyMonette/TheWitcherTRPG/issues/282.
