### ISSUE TITLE
Any possibility to add compatibility with Item piles module?

### ISSUE THREAD

**Issue by RKMkovi** [AnthonyMonette/TheWitcherTRPG#295]
https://foundryvtt.com/packages/item-piles

There is a how to do it guide in their wiki: 
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/new?assignees=Haxxer&labels=enhancement&template=system-request.md&title=%5BSYSTEM%5D+-+Write+the+system%27s+name+here

I have tried to do it myself but I have zero skills or knowledge about programming.

**Comment by ortegamarcel** [comment]
What exactly is the problem? I am also using Item piles and it works fine.

**Comment by Melkkart** [comment]
Yes, 
![image](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/31ad0ba5-4ff5-450a-99f7-f39e13b403fe)
Currency ...
![image](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/57da2034-9ac4-4f8d-8aca-651713aadbab)
Secundary Currencies ...
![image](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/bc7a0354-3508-4856-bf20-61144c03782f)
