### ISSUE TITLE
[Bug] Vendor dont Work correctly

### ISSUE THREAD

**Issue by Melkkart** [AnthonyMonette/TheWitcherTRPG#305]
I think this problem has arisen when creating new categories for objects. 
I had created stores that sold items to players, now many items have disappeared, after a lot of looking, they are items that have been sorted into new categories. Weapons are still in the vendor, but for example diagrams have disappeared. 
When I try to drag the diagram again, it doesn't appear and I can't create new ones in the vendor. 

Weapons Dealer: 
![2](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/215b7e0a-113f-4e19-89c9-2438a1747f45)

I am trying to drag a diagram : (Nothing happens)
![3](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/5a96533d-e6a9-4542-946b-6f269ed2913e)

I try to create one of each: (Just create some)
![4](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/8d97d551-57e9-41e7-8408-25102e9915cd)

**Comment by AnthonyMonette** [comment]
Is it still an issue? I tried it on my side and it seems to work fine.  Please let me know if you are still experiencing this issue

**Comment by Melkkart** [comment]
Si, ya va bien, gracias!
