### ISSUE TITLE
Issue with enchanted item rolls

### ISSUE THREAD

**Issue by pedroaugustobt** [AnthonyMonette/TheWitcherTRPG#313]
I have a problem, when I put an enchanted item on the weapon, the dice roll does not work.

this is the bug that appears:
![Captura de tela 2023-07-09 204250](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/107325727/3c087f0f-77cc-4c01-9b05-67fc0f151dba)

Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'quantity')
[Detected 1 package: system:TheWitcherTRPG]
    at Array.sum (WitcherActorSheet.js:94:45)
    at WitcherActorSheet._onItemRoll (WitcherActorSheet.js:2052:34)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by Melkkart** [comment]
![image](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/0ebcb993-ad6e-45f7-883a-930079e7bf51)

It works fine for me, try the version with the improvements made by Ortegamarcel and Pkonshik, if you don't want to make all the changes, here is the system.
https://drive.google.com/file/d/15VY9Yti3UqaLuRqkYtTK7Z4SduLOD9bL/view?usp=sharing

**Comment by pedroaugustobt** [comment]
@Melkkart 
does this file already have the spells, items ready or is it just the system with the bugs corrected?

**Comment by AnthonyMonette** [comment]
@pedroaugustobt can you confirm if with the latest version it works properly?

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt can you confirm if with the latest version it works properly? 

Yes, working in latest version! I have some fixes about glyphs and focus. Can i send pull?

**Comment by AnthonyMonette** [comment]
Yes, of course, I`m gonna close this issue and I`ll take a look at your PR once it will be send Thanks!
