### ISSUE TITLE
Active Effects bugged Monster Sheet

### ISSUE THREAD

**Issue by RusselH3X** [AnthonyMonette/TheWitcherTRPG#314]
When I added an active effect on a Monster, it bugged the sheet and is now preventing me from removing or adding new ones. Not only Active Effect but any item on the Skills, Att/Loot, Details and Spells pages.

**Comment by Melkkart** [comment]
I think it's your version of the system, try this one, which already has the latest changes made by Ortegamarcel and Pkonshik.
https://drive.google.com/file/d/15VY9Yti3UqaLuRqkYtTK7Z4SduLOD9bL/view?usp=sharing

**Comment by RusselH3X** [comment]
Installed the new version manually. Unfortunately, the bug keeps happening.

**Comment by RusselH3X** [comment]
Installed the dev branch of the system. Bug seems to be fixed. Thanks and keep up the great work!
