### ISSUE TITLE
Change the number

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#32]
- Change the number and the weight is calculated.

- add one of the same kind and update the number

**Comment by AnthonyMonette** [comment]
I,m not really sur qhat you are talking aout here.  Which number is to change? In which sheet

**Comment by Ulvtand** [comment]
Explanation: I add 3x tents to my character. I want to see the sum of the weight. ;)

**Comment by Ulvtand** [comment]
Similar to # 33 yes.
