### ISSUE TITLE
Initiative Issue v.0.99

### ISSUE THREAD

**Issue by Melkkart** [AnthonyMonette/TheWitcherTRPG#341]
The initiative button does not function correctly. When pressed on the character sheet, the player enters combat, but the initiative is not rolled (sometimes it is), but if attempted again, it no longer works. Once this occurs, it's no longer possible to add more NPCs to combat nor roll initiative, even if clicked, it does not function. (No Modules)

![image](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/123239719/802ab87a-28d6-44f5-8675-4a7fad877f6f)

**Comment by Stexinator** [comment]
fixed on my fork. I also accept issues if you want to report it directly to me

**Comment by Melkkart** [comment]
Thks man
