### ISSUE TITLE
random loot

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#40]
in monster sheet, under Loot, wishes to be able to enter [[1d10]] and get it rolled when you drag and drop to the character

**Comment by Ulvtand** [comment]
It is also good that, for example, when you drag and drop "mundane item", which item is rolled

**Comment by AnthonyMonette** [comment]
It works now but for the mundane item, there is a table that you can roll. THe GM should roll it in advance, in my option, so that it would be transparent to the players
