### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#41]
Shouldn't Vulnerabilities have its own box, since all monsters have it?

**Comment by AnthonyMonette** [comment]
I Tried to stay true to the layout in the Witcher journals.  That includes the suceptibilities section and the vulnerabilities that requires more descriptions are describe as a Note, to leave enough space for the description

**Comment by Ulvtand** [comment]
I like that you try to keep the original layout. But in the book, Vulnerabilities has its own place, as do Abilities. None of them, as I see it, are note. Or are you going for another original? Now when I look in A Witcher Journal I see the difference! I started with The Witcher and the layout is different. I understand your choice and agree.

**Comment by Ulvtand** [comment]
I miss two points: Intelligence & Senses
