### ISSUE TITLE
Autoroll damage for damage spells

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#42]
Add so you can put damage on spells witch can be rolled directly in chat

**Comment by Ulvtand** [comment]
Why not for all injuries? As long as it is easily read and you do not want to use it, you can skip it.

**Comment by Ulvtand** [comment]
In WFRP, GM can apply the damage directly to the target, with a button. Is it possible to add to Witcher?

**Comment by VelithOzy** [comment]
> In WFRP, GM can apply the damage directly to the target, with a button. Is it possible to add to Witcher?

I doubt it. Before the rolled damage is applied there's math involved, sometimes 3 layers of math.
There would need to be fully automated target system for you to apply the correct damage with a button. But one can dream...

**Comment by AnthonyMonette** [comment]
In the current witcher system when the damage is displayed in the chat, you must substract the SP of your Armor and then apply the location modifier.  This could be complicated (Not impossible) having the defender to input the SP of his armor Then automaticly apply the location mudifier

**Comment by Ulvtand** [comment]
> In the current witcher system when the damage is displayed in the chat, you must substract the SP of your Armor and then apply the location modifier. This could be complicated (Not impossible) having the defender to input the SP of his armor Then automaticly apply the location modifier

True, but by no means impossible. For example, PC marks which NPC they want to attack, where you already have which SP and the location modifier. My dream is to make it work, more than happy to help. :)
