### ISSUE TITLE
Drag on drop Items in inventory broken

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#44]
can't seem to be able to Drag on drop Items into the inventory

**Comment by Ulvtand** [comment]
I have no problem with that.

**Comment by Batziy** [comment]
The dev version still has async _onDrop(event) while Main has async _onDrop(event, data). Only the latter works and im using the dev version

**Comment by Batziy** [comment]
Dev is 6 commits behind Main witch it should not be :P

**Comment by AnthonyMonette** [comment]
My bad :S
