### ISSUE TITLE
Weapon as loot

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#46]
Is it possible to make so that weapons can be placed as loot?

**Comment by Ulvtand** [comment]
armor can be added to the loot

**Comment by AnthonyMonette** [comment]
Armor already go automaticly in the loot of a monster. And I'm wondering why would it be place in the loot section? They currently are separated because you can make action with the weapons.  not with the loot

**Comment by Ulvtand** [comment]
Now I do not quite remember why I wrote it.
Since I can not say that it is an Issues, close no 46
