### ISSUE TITLE
Monster type

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#48]
How do I change the monster type?
![Skärmbild 2021-07-01 090710](https://user-images.githubusercontent.com/82996726/124081509-ee478900-da4b-11eb-80eb-2b9477c08173.png)

**Comment by AnthonyMonette** [comment]
You change it with the Category at the top right  of the monster sheet.

**Comment by AnthonyMonette** [comment]
@Ulvtand is this still a problem, I cannot reproduce the issue
