### ISSUE TITLE
Continuation of # 48

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#56]
I do not get the "creature image". The icon remains "wrong" as in the image in # 48

**Comment by AnthonyMonette** [comment]
Is it still An issue? because I can't reproduce the problem

**Comment by Ulvtand** [comment]
![image](https://user-images.githubusercontent.com/82996726/129250188-85611642-8f92-4593-bb52-cd6deca5dc95.png)
![image](https://user-images.githubusercontent.com/82996726/129250221-bb226d84-99a5-459b-b659-5955464eea04.png)
Whatever I choose for the type of creature, I get this picture

**Comment by Batziy** [comment]
Is the pictures located in the /TheWitcherTRPG/assets/images/monsters folder? if they are do you get any error message in the foundry console?

**Comment by Ulvtand** [comment]
Yep, they're there.
![image](https://user-images.githubusercontent.com/82996726/129282808-3f0c6226-2c36-4d7a-aea9-cf264353736a.png)
