### ISSUE TITLE
Change monster skill list

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#61]
I feel that the monster skill list is a bit messy. lot of expanding and minimizing. and a lot of monster don't "have" a lot of skills. Was thinking is one could maybe just have an alphabetical list and a cogwheel options that opens new window where you can change witch skills is displayed in the list? feels like an alphabetical list would also be better since they are display them like it in the books.

**Comment by VelithOzy** [comment]
I second this.

Expandable alphabetical list would be easier to copy from the bestiary/create. Then collapse into the ranked skills only.

**Comment by AnthonyMonette** [comment]
Having a skill with no points in it doesn't mean that you cannot roll this skill. 
So, in my opinion, every monsters needs every skills.

**Comment by Batziy** [comment]
True but some skills is more relevant. I nekker don't realy use crafting/seduction/business/sailing that often. so would be nice if you could hide them.

**Comment by Dillatr** [comment]
Maybe a button that gives a pop-up box with a checkbox list of all the skills, allowing you to select certain skills to hide from the rollable skills list?
