### ISSUE TITLE
Weapons breaking with Enhancement Field

### ISSUE THREAD

**Issue by VelithOzy** [AnthonyMonette/TheWitcherTRPG#86]
Weapons break after you add any number to the Enhancement field, they wont roll to hit anymore even if you remove the number. Error:

![image](https://user-images.githubusercontent.com/89222757/130138340-0c53fd54-74bd-4e20-8c6b-e186d7f59530.png)

Easy to replicate, create a new weapon > roll > add any number to the enhancement field > try to roll again.
No modules.

**Comment by AnthonyMonette** [comment]
I just tried and it works, Can you confirm that the problem is solved on your side?

**Comment by VelithOzy** [comment]
Fixed! They don't break anymore.
