### ISSUE TITLE
Display details when rolling dice : 1d10+ 2[stat]+4[skill]-3[parry]

### ISSUE THREAD

**Issue by AnthonyMonette** [AnthonyMonette/TheWitcherTRPG#95]

**Comment by tinkerghost** [comment]
The issue I see is that dice rolls don't appear to come from [stat] but rather from the [mod] derived from the stat & I'm not seeing where the 'mod' comes from in the book.

From the book (p57), skill checks should be the raw stat [1-10] + skill [1-10] + 1D10.

Opposing An Antagonist
When facing an opponent, you roll
1d10 and add your skill level and appropriate
Stat level. You then compare
this to your opponent. Whoever has
rolled higher wins. If the rolls are equal,
then the defender wins.

![Witcher-stat block](https://user-images.githubusercontent.com/38480075/132138249-2751a674-cf44-4c37-93c2-920b7ead52b1.png)
