### ISSUE TITLE
Some attack skills are not rolling with the correct statistic

### ISSUE THREAD

**Issue by TheC0MMAND0** [AnthonyMonette/TheWitcherTRPG#98]
A couple of the Attack skills for the monster sheets are not rolling with the proper statistics. 

The Skills themselves are rolling with the correct statistics, but when the attack skill is selected when creating their weapons the incorrect statistic is being used. Brawling, Melee, Small Blades, Staff/Spear and Swordsmanship are rolling with DEX instead of REF.

**Comment by AnthonyMonette** [comment]
Have you checked the box specifying it's a melee weapon?

**Comment by AnthonyMonette** [comment]
This can be confusing tho, i'll make it roll depending on the skill choosen instead of the melee speification

**Comment by TheC0MMAND0** [comment]
Yeah, after ticking the "Melee Bonus" box for the weapon it does roll with REF instead of DEX. The confusion for me comes from the tick box being labeled "Melee Bonus" rather than just "Melee", to my understanding, monsters don't get a "Melee bonus" like the players do. 

Having it roll with the chosen skill rather than the melee specification would be great. 

Thanks!
